name: Generate Snake

on:
  # # schedule:
  # #   - cron: '0 0 * * *'  # Runs the workflow daily at midnight UTC
  push:
    branches:
      - main  # Runs the workflow whenever there is a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Set up Git user
        run: |
          git config --global user.email "shaswatshah51@gmail.com"
          git config --global user.name "sdshah09"
      
      - name: Update README with new snake
        run: |
          sed -i 's|<img alt="github-snake" src="https://github.com/sdshah09/raw/output/github-snake.svg" />|<img alt="github-snake" src="https://github.com/'${{ github.repository_owner }}'/'${{ github.repository }}'/raw/output/github-snake.svg" />|' README.md
          git add README.md
          git add dist/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update snake animation"
      
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
